package data_load.readers;


public class Res_de extends java.util.ListResourceBundle {
	static final Object[][] contents = new String[][] {
			{ "reading", "Lese " },
			{ "Uncomatible_RMinSize", "Inkompatibler RMin Gr��enwert: " },
			{ "Uncomatible_RTileType", "Inkompatibler RTile Typuswert: " },
			{ "Exception_reading", "Ausnahme beim Raster lesen: " },
			{ "raster", "Raster" },
			{ "The_raster_has_been", "Das Raster wurde geladen von " },
			{ "Error_accessing", "Zugriffsfehler " },
			{ "Select_the_file_with", "W�hle die Datei mit den Rasterdaten" },
			{ "The_data_source_for", "Die Datenquelle f�r den Layer ist nicht spezifiziert!" },
			{ "Start_reading_raster", "Starte das lesen der Rasterdaten von " },
			{ "Reading_data_from", "Lese Daten aus dem ASCII Format" },
			//Was ist gemeint mit Data sample?
			{ "Data_sample_", "Datensatz:" },
			// Was ist ein Value separator?
			{ "Value_separator_", "Begrenzungszeichen:" },
			{ "Take_field_types_from", "Benutze die Feldtypen aus der Reihe N" },
			{ "_N_numeric_C", "(N - Numerisch, C - Buchstaben, L - Logsich, D - Datum)" },
			{ "Take_field_names_from", "Benutze die Feldnamen aus der Reihe N" },
			{ "Identifiers_are_in", "Identifier sind im Feld " },
			{ "_enter_the_name_or", "(Geben Sie den Namen oder die Nummer des Feldes ein)" },
			{ "If_there_is_no_field", "Wenn keine Felder mit Identifiern vorhanden sind," },
			{ "the_system_will", "erzeugt das System nicht erscheinde Identifier aus den Datensatznummern" },
			{ "Names_of_entities_are", "Namen der Entities sind im Feld" },
			{ "_enter_name_or_number", "(Geben Sie den Namen, die Nummer oder nichts ein)" },
			{ "Coordinates_of", "Koordinaten der Entities sind in den Feldern" },
			{ "_enter_names_or", "(Geben Sie Namen oder Nummern ein)" },
			{ "Cancel", "Abbrechen" },
			{ "No_separator", "Kein Seperator ausgew�hlt!" },
			{ "The_separator_must_be", "Der Seperator muss ein Buchstabe sein!" },
			{ "Illegal_number_of_the", "Ung�ltige Nummer der Reihe mit den Feldtypen!" },
			{ "Illegal_number_of_the1", "Ung�ltige Nummer der Reihe mit den Feldnamen!" },
			{ "Illegal_number_of_the2", "Ung�ltige Nummer der Reihe mit den Identifiers der Entities!" },
			{ "Illegal_number_of_the3", "Ung�ltige Nummer der Reihe mit den Entities!" },
			{ "Name_of_the_field", "Name des Feldes mit der X-Koordinate ist nicht spezifiziert!" },
			{ "Name_of_the_field1", "Name des Feldes mit der Y-Koordinate ist nicht spezifiziert!" },
			{ "Select_the_file_with1", "W�hle die Datei mit der Tabelle" },
			{ "The_table_data_source", "Die Tabellendatenquelle ist nicht spezifiziert!" },
			{ "The_delimiter_is_not", "Der Delimiter ist nicht spezifiziert f�r " },
			{ "Start_reading_data", "Starte lesen der Daten von " },
			{ "reading_metadata_from", "lese Metadaten von " },
			{ "Metadata_got_from", "Metadaten bekommen von " },
			{ "Unrecognizable_number", "Nicht identifizierbare Zahl der Reihe mit Feldnamen!" },
			{ "Unrecognizable_number1", "Nicht identifizierbare Zahl der Reihe mit Feldtypen!" },
			{ "Unrecognizable_number2", "Nicht identifizierbare Zahl der Reihe mit Identifiern!" },
			{ "Unrecognizable_number3", "Nicht identifizierbare Zahl der Spalte mit den Namen!" },
			{ "Exception_reading1", "Ausnahme beim lesen der Metadaten: " },
			{ "No_METADATA_END", "Kein METADATA_END Indikator gefunden!" },
			{ "skipping_the_header", "�bersprang den Kopf(Header) der Datei " },
			{ "Metadata_end_found_in", "Metadatenende gefunden in " },
			{ "attribute_names", " Attributnamen" },
			{ "Got", "Bekam " },
			{ "attribute_types", " Attributtypen" },
			{ "data_lines_read", " Datenreihen gelesen" },
			{ "Data_loaded_N_of_rows", "Daten geladen; N Reihen: " },
			{ "_N_of_fields_", "; N Felder: " },
			{ "_no_data_loaded", "; keine Daten geladen" },
			{ "Unexpected_end_of", "Unerwartetes Ende der Daten " },
			{ "Error_reading_data_", "Fehler beim lesen der Daten: " },
			{ "Determining_attribute", "Bestimme Attributtypen..." },
			{ "Finished_determining", "Bestimmung der Atributtypen beendet in " },
			{ "rows", " Reihen" },
			//Der Zusammenhang wird hier nicht klar
			{ "of", " of " },
			{ "Read", "lese " },
			{ "Cannot_get_access_to", "Zugang zur Zwischenablage verweigert" },
			{ "No_data_in_the", "Keine Daten in der Zwischenablage!" },
			{ "Cannot_get_data_from", "Bekomme keine Daten aus der Zwischenablage: " },
			{ "Start_reading_data1", "Starte lesen der Daten aus der Zwischenablage" },
			{ "Data_from_clipboard_", "Daten aus der Zwwischenablage (" },
			{ "Data_preview", "Datenvorschau" },
			{ "No_data_available", "Keine Daten verf�gbar" },
			{ "Data_content_", "Dateninhalt:" },
			{ "_set_name_or_number", "(Geben Sie Name, Nummer oder nichts ein)" },
			{ "Illegal_name_of_the", "Ung�ltiger Name des Feldesmit den Identifiern der Entities!" },
			{ "The_name_or_number_of", "Der Name oder die Nummer des X-Koordinatenfeldes ist nicht spezifiziert!" },
			{ "Illegal_number_of_the4", "Ung�ltige Nummer des X-Koordinatenfeldes!" },
			{ "Illegal_name_of_the1", "Ung�ltiger Name des X-Koordinatenfeldes!" },
			{ "The_name_or_number_of1", "Der Name oder die Nummer des Y-Koordinatenfeldes ist nicht spezifiziert!" },
			{ "Illegal_number_of_the5", "Ung�ltige Nummer des Y-Koordinatenfeldes!" },
			{ "Illegal_name_of_the2", "Ung�ltiger Name des X-Koordinatenfeldes!" },
			{ "Trying_to_open_the", "Versuche URL zu �ffnen " },
			{ "Could_not_open", "Konnte nicht �ffnen " },
			{ "Wrong_file_format_", "Falsches Datenformat: " },
			//Unter dem dbfreader, ist allerdings nicht ausgetauscht. Erstmal stehen lassen, falls Fehler auftauchen.
			//{ "single_char_1", "D" },
			//{ "single_char_2", "L" },
			//{ "single_char_3", "N" },
			{ "Exception_reading2", "Ausnahme beim lesen des Dateikopfes (Header): " },
			{ "records_of", " Ordner von " },
			{ "Exception_", "Ausnahme: " },
			//Bedeutung?
			{ "sample_records_of", " sample records  of " }, { "reading_raster_from", "Lese Raster von " }, { "has_been_loaded", " wurde geladen" }, { "The_raster", "Das Raster " }, { "Specify_the", "bestimme die geographischen Grenzen:" },
			{ "X1_not_specified_", "X1 wurde nicht angegeben!" }, { "Illegal_text_for_X1_", "Ung�ltiger Text f�r X1!" }, { "X2_not_specified_", "X2 wurde nicht angegeben!" }, { "Illegal_text_for_X2_", "Ung�ltiger Text f�r X2!" },
			{ "X2_must_be_bigger", "X2 mu� gr��er sein als X1!" }, { "Y1_not_specified_", "Y1 wurde nicht angegeben!" }, { "Illegal_text_for_Y1_", "Ung�ltiger Text f�r Y1!" }, { "Y2_not_specified_", "Y2 wurde nicht angegeben!!" },
			{ "Illegal_text_for_Y2_", "Ung�ltiger Text f�r Y2!" }, { "Y2_must_be_bigger", "Y2 muss gr��er sein als Y1!" }, { "Select_the_file_with2", "Bestimme die Datei mit den Daten" },
			{ "The_data_source_is", "Die Datenquelle ist nicht angegeben!" }, { "Reading_data_from1", "Lese Daten von " },
			{ "attributes", " Attribute" },
			{ "_got", ": bekommen " },
			{ "table_records", " Tabellenordner" },
			{ "geographic_objects", " geographische Objekte" },
			{ "Could_not_get", "Bekomme keine geographischen Daten von " },
			{ "Select_the_file_with3", "Datei mit den geographischen Daten angeben" },
			{ "are_not_specified_", " sind nicht markiert!" },
			{ "The_bounds_of_layer", "Die Grenzen der Layer " },
			//Fall nicht klar (der oder des)
			{ "Bounds_of", "Grenzen der " }, { "Start_loading_image", "Starte das Laden des Bildes von " }, { "Cannot_load_an_image", "Kann kein Bild laden von " }, { "image", "Bild" }, { "The_image_has_been", "Das Bild wurde geladen von " },
			{ "_reading_finished", ": Lesen beendet" }, { "Error_", "Fehler: " }, { "Reading_the", "Lese Koordinaten..." }, { "contours_read", " Umrisse gelesen" }, { "Corruption_found_in", "Fehler in der Datenspezifikation gefunden" },
			{ "spatial_entities", " r�umliche Entities geladen" }, { "No_spatial_entities", "Keine r�umliche Entities geladen!" }, { "No_reader_found_for", "Kein Reader f�r MID Daten gefunden!" },
			{ "_reading_the_bounding", ": lese begrenzendes Rechteck..." }, { "Exception_reading3", "Ausnahem beim lesen der Geodaten: " }, { "_reading_the", ": lese Koordinaten..." }, { "objects_got", " Objekte bekommen" },
			{ "_no_spatial_entities", ": keine r�umlichen Entities geladen!" }, { "No_reader_found_for1", "Kein Reader f�r die Daten gefunden " }, { "Reading_the_bounding", "Lese begrenzendes Rechteck..." }, { "shapes_read", " Shapes gelesen" },
			{ "Could_not_get_any", "Bekomme keine Objekte von " }, { "geographic_entities", " geographische Entities von " }, { "got", "Bekam " }, { "Could_not_get_points", "Could not get point objects from the table " },
			{ "_no_coord_", ": keine Koordinaten gefunden!" }, { "constr_point", " Punktobjekte konstruiert: " }, { "_obj_constructed", " Objekte konstruiert" },
			{ "make_new_index_file", "Wollen Sie diese Datei mit tfw-Dateien neu erstellen oder aktualisieren ?" } };

	public Object[][] getContents() {
		return contents;
	}
}
