package spade.analysis.calc;

public class Res_de extends java.util.ListResourceBundle {
	static final Object[][] contents = new String[][] {
			{ "Results_of_the", "Die Ergebnisse der Berechnung werden " },
			{ "stored_in_the", "in der Datenbank als neue Attribute gespeichert." },
			{ "You_may_edit_names_of", "Sie k�nnen die Namen der neuen Attribute " },
			{ "and_their_values_", "sowie ihre Werte editieren:" },
			{ "Attribute_names", "Attributnamen" },
			{ "Computes_the", "Berechnet das arithmetische Mittel von " },
			{ "values_of_two_or_more", "zwei oder mehr Attributwerten in jeder Tabellenzeile." },
			{ "Select_at_least_two", "W�hlen Sie mindestens zwei numerische Attribute " },
			{ "for_average", "f�r die Berechnung der arithmetischen Durchschnittswerte " },
			{ "Calculations_in_table", "Tabellenberechnungen" },
			{ "Sum_of_columns", "Summen mehrerer Spalten" },
			{ "Percentages_and", "Prozent- und Verh�ltniszahlen" },
			{ "Change_difference", "�nderung und Verh�ltnis" },
			{ "Arbitrary_formula", "Formelberechnungen" },
			{ "Average_among_columns", "Mittelwerte mehrerer Spalten" },
			{ "Variance_among", "Varianz zwischen Spalten" },
			{ "Count_value", "Werte z�hlen" },
			{ "Weighted_average", "gewichtetes Mittel mehrerer Spalten" },
			{ "Rule_validation", "Rule validation" },
			{ "Ideal_Point_Analysis", "Ideal-Point Analyse" },
			{ "Values_Order", "Werte -> Rang" },
			{ "Ordered_Weighted", "Gewichtetes Mittel des Rangs" },
			{ "Similarity_distance_", "�hnlichkeit (Distanz)" },
			{ "Similarity", "�hnlichkeit (Klassifikation)" },
			{ "Dominant_attribute", "Klassifikation dominanter Attribute" },
			{ "For_two_numeric", "Berechnet f�r zwei oder mehr Attribute " },
			{ "arithmetic_difference", "die arithmetische Differenz, oder ihr Verh�ltnis, oder die Differenz zu einem " },
			{ "of_the_attributes_", "weiteren Attribut." },
			{ "Select_exactly_two", "W�hlen Sie genau zwei numerische Attribute " },
			{ "for_the_computation1", "f�r die Berechnung ihrer absoluten oder relativen Differenzen oder ihres Verh�ltnisses" },
			{ "For_each_table_row", "F�r jede Tabellenzeile wird " },
			{ "more_selected", "das jeweils durch seine Werte dominierende Attribut gefunden. Verschiedene " },
			{ "dominance_measures", "Dominanzma�e sind m�glich.\n Das Ergebnis liefert 2 neue Attribute: " },
			{ "1the_dominating", "1) das dominierende Attribut (qualitativ); 2) Der Grad der Dominanz (numerisch)." },
			{ "for_dominance", "f�r die Berechnung der jeweils dominanten Werte." },
			{ "Divides_values_of", "Teilt die Werte jedes selektierten Attributes " },
			{ "attributes_by_values", "durch die Werte eines weiteren selektierten Attributes, oder durch die Summe " },
			{ "of_these_attributes", "dieser Attributwerte, oder durch eine bestimmte Zahl. Eignet sich f�r die Berechnung " },
			{ "proportions_of_parts", "von Verh�ltniszahlen." },
			{ "Select_one_or_more", "W�hlen Sie mindestens ein numerisches Attribut " },
			{ "to_be_divided_by", "das durch eine weiteres Attribut (sp�ter ausw�hlbar), oder durch " },
			{ "sum_of_these", "die Summe der Attributwerte, oder eine feste Zahl (sp�ter ausw�hlbar) geteilt werden soll." },
			{ "Normalize_attributes_", "Attribut-Normalisierung:" },
			{ "divided_by", "geteilt durch" },
			{ "their_sum", "Summe" },
			{ "Select_attribute", "W�hlen Sie ein Attribut aus" },
			{ "number_", "Zahl:" },
			{ "Compute_percentages", "Berechnung von Prozent- oder Verh�ltniszahlen" },
			{ "divided_by1", " geteilt durch " },
			{ "sum", "Summe" },
			{ "Attribute", "Attribut" },
			{ "Orders_table_rows", "Ordnet Tabellenzeilen nach " },
			{ "descending_order_of", "abnehmenden Werten eines numerischen Attributes und erstellt ein neues " },
			{ "integer_attribute", "ganzzahliges Attribut, das den Rang jeder Tabellenzeile darstellt." },
			{ "Select_exactly_one", "W�hlen Sie genau ein numerisches Attribut " },
			{ "for_finding_the_order", "um den Rang f�r jede Zeile zu errechnen." },
			{ "Select_ordering", "W�hlen Sie die Ordnungsrichtung:" },
			{ "Decrease", "Abnehmend" },
			{ "Increase", "Zunehmend" },
			{ "Ordering", "Anordnen" },
			{ "order_", " Rang: " },
			{ "Aggregates_values_of", "Aggregates values of multiple criteria into a single evaluation " },
			{ "score_according_to_a", "score according to a user-defined decision strategy" },
			{ "representing_criteria", "als Kriterien f�r die Einsch�tzung" },
			{ "Rule_Validator", "Rule Validator Scatter Plot" },
			{ "Computes_the_degree", "Berechnet den �hnlichkeitswert, d.h. die Distanz " },
			{ "of_each_object", "jedes Objektes (entspricht einer Tabellenzeile) zu einem selektierten Objekt oder " },
			{ "agroup_of_objects_The", "einer Objektgruppe. Die jeweilige Distanz bezieht sich also auf die Werte der " },
			{ "selected_attributes_", "ausgew�hlten Objekte." },
			{ "for_the_estimation_of", "f�r die Berechnung der �hnlichkeit zwischen Objekten." },
			{ "Special_metric_for", "Special metric for time series data.\nIt reflects number of time moments\n with similar change of values.\n\nDo not use with non-temporal data !" },
			{ "Determines_for_each", "Jedes Objekt (bestimmt durch eine" },
			{ "one_table_row_to", " Tabellenzeile) wird der jeweils �hnlicheren von zwei Objektgruppen (bestimmt durch zwei selektierte Objekte als Mittelpunkte)zugeordnet. " },
			{ "is_closer_more", "Die jeweilige Distanz bezieht sich also auf die Werte der " },
			{ "for_the_estimation_of2", "f�r die Berechnung der �hnlichkeit zwischen Objekten." },
			{ "Special_metric_for2", "Spezielle Metrik f�r Zeitreihen.\nSie berechnet die Anzahl an Momenten\n" + "mit �hnlichen Wert�nderungen.\n\nNur f�r Zeitreihen verwenden !" },
			{ "Sum_of", "Summe von " },
			{ "Computes_the1", "Berechnet die Summe von " },
			{ "for_the_computation2", "f�r die Berechnung der arithmetischen Summe ihrer Werte." },
			{ "For_a_group_of", "F�r eine Gruppe homogener Attribute wird " },
			{ "calculates_in_each", "in jeder Tabellenzeile das Auftreten jedes Wertes gez�hlt. " },
			{ "Produces_as_many_new", "Erstellt neue Attribute entsprechend der Anzahl unterscheidbarer Werte aller " },
			{ "selected_attributes", "selektierten Attribute. Anwendbar auf Attribute mit kleiner Anzahl " },
			{ "of_possible_values_", "m�glicher Werte." },
			{ "Select_two_or_more", "W�hlen Sie mindestens zwei homogene Attribute " },
			{ "for_counting_value", "um das Auftreten von Werten in einer Tabellenzeile zu z�hlen." },
			{ "Number_of_different", "Anzahl verschiedener Werte ist zu gro�: >=" },
			{ "Variance_", "Varianz: " },
			{ "Computes_the3", "Berechnet die statistische Varianz zwischen " },
			{ "for_the_computation3", "f�r die Berechnung der statistischen Varianz ihrer Werte " },
			{ "Weighted_average1", "Berechnung des gewichteten Mittels" },
			{ "Calculates_weighted", "Berechnet das gewichtete Mittel f�r mehrere Attribute" },
			{ "Select_at_least_two1", "W�hlen Sie mindestens zwei numerische Attribute aus." },
			{ "Formula_with_", "Formel mit " },
			{ "Sum_of", "Summe von" },
			{ "Aver", "Mittel: " },
			{ "Arith", "Arithmetische Berechnungen" },
			{ "Stat", "Statistische Berechnungen" },
			{ "Decis", "Entscheidungshilfen" },
			{ "Mult", "Mehrdimensionale Analyse" },
			{ "Cannot1", "Cannot construct a calculator for the method " },
			{ "Cannot2", "Cannot construct a calculator: " },
			{ "Wrong", "Wrong method identifier: " },
			{ "The_method", "Die Methode " },
			{ "isnotav", " ist nicht verf�gbar!" },
			{ "isnotap", " ist auf die ausgew�hlten Attribute nicht anwendbar!" },
			{ "calcerr", "Berechnungsfehler!" },
			{ "unkncalcm", "Unbekannte Rechenmethode: " },
			{ "isnotf", " wurde unter den verf�gbaren Methoden nicht gefunden" },
			{ "inappds", "Unangemessene Datenquelle; Datentabelle ist n�tig!" },
			{ "nonorm", "Keine Normalisierung (absolute Werte)" },
			{ "Med", "Median and Quartile" },
			{ "Mea", "Mittel und Standardabweichung" },
			{ "Att1", "Attribute werden auf einer einzigen Skala ihrer absoluten Werte dargestellt ohne Normalisierung." },
			{ "Att2", "Attribute werden normalisiert auf einer Skala von 0 bis 1, sodass 0,0 dem Minimum entspricht und 1,0 dem Maximum jedes Attributes." },
			{ "Att3", "Attribute werden auf einer Skala dargestellt mit dem jeweiligen Median im Zentrum sowie den entsprechend ausgerichteten Quartilen." },
			{ "Att4", "Attribute werden auf einer Skala dargestellt mit dem jeweiligen Mittelwert im Zentrum und der entsprechend ausgerichteten Standardabweichung." },
			{ "Domacalc", "Bestimmung der dominanten Attribute" },
			{ "Computes_the4", "Berechnet eine beliebige Formel " },
			{ "involving_arithmetic", "mit arithmetischen Konstanten, den Attributwerten jeder Tabellenzeile, " },
			{ "of_the_table_and", "und elementaren mathematischen Funktionen" },
			{ "Select_at_least_one", "W�hlen Sie mindestens ein numerisches Attribut " },
			{ "for_the_computation4", "f�r die Berechnung der Summe je Attribut." },
			{ "Specify_the_formula", "Geben Sie die Formel an" },
			{ "Invalid_formula_", "Ung�ltige Formel!" },
			{ "Formula_with", "Formel mit " },
			{ "ordwa", "Gewichtete Mittelung von R�ngen" },
			{ "order_weights", "Gewichtungen ordnen" },
			{ "Criterion_weights", "Kriterium ordnen" },
			{ "classres", "Ergebnisse klassifizieren" },
			{ "Close", "Schlie�en" },
			{ "Wfhv", "Gewichtung nach h�chsten Werten" },
			{ "Wflv", "Gewichtung nach niedrigsten Werten" },
			{ "Uscow", "Use slider to change this order weight" },
			{ "Sowfh", "Set order weight for highest weighted standardized criterion value of each alternative" },
			{ "Sowfl", "Set order weight for lowest weighted standardized criterion value of each alternative" },
			{ "Sowfi", "Set order weight for an intermediate criterion value of each alternative" },
			{ "stwlc", "Set to WLC" },
			{ "Sewff", "Set equal weights for full tradeoff between good and bad values" },
			{ "Sta", "Set to AND" },
			{ "Gfww", "Give full weight to worst value of each alternative (pessimistic strategy)" },
			{ "Random", "Random" },
			{ "Srow", "Set random order weights" },
			{ "Sto", "Set to OR" },
			{ "Gfwb", "Give full weight to best value of each alternative (optimistic strategy)" },
			{ "Risk", "Risk" },
			{ "Dispersion", "Dispersion" },
			{ "Tradeoff", "Tradeoff" },
			{ "Irbiww", "Increase risk by increasing weight of best value" },
			{ "rrbiw", "Reduce risk by increasing weight of worst value" },
			{ "It", "Increase tradeoff by reducing maximal weight" },
			{ "Rt", "Reduce tradeoff by increasing maximal weight" },
			{ "Id", "Increase dispersion by reducing maximal weight" },
			{ "Rd", "Reduce dispersion by increasing maximal weight" },
			{ "Sorry", "Sorry, adding/removing attributes currently not supported in OWA" },
			{ "ErrorOWA", "Error in Ordered Weighted Averaging method" },
			{ "Ccrd", "Berechnung von Ver�nderung / Verh�ltnis / Differenz" }, // ChangeCalc
			{ "Fta", "F�r folgende Attribute:" },
			{ "Invert", "Vertauschen" },
			{ "Cc", "Berechnung von �nderungen etc." },
			{ "Dominant:", "Dominant:" }, //Dominance Calc
			{ "Tod", "Dominanztyp ?" },
			{ "Maximum", "Maximum" },
			{ "Minimum", "Minimum" },
			{ "An", "Attribut Standardisierung ?" }, //"Attribute normalization"
			{ "Auic", "In den Berechnungen  verwendete Attribute:" },
			{ "Lstw", "\"Let's shake the weights !\"" }, //IdealPointCalc
			{ "ibw", "Iterationen zwischen Gewichtungen" },
			{ " and", " und" },
			{ "wsbnn", "Gewichtung sollte nicht negativ sein" },
			{ "cwsbbmm", "momentane Gewichtung sollte zwischen Min und Max liegen" },
			{ "wnitnf", "Falsche Zahl im numerischen Feld" },
			{ "wsblt", "Gewichtung sollte weniger als 1.0 sein" },
			{ "wnoi", "Falsche Anzahl an Iterationen" },
			{ "Supportsmcs", "Unterst�tzt multi-kriterielle Auswahl: Bindet " },
			{ "vosa", "die Werte verschiedener Attribute (Selektionskriterien) in eine einzige Werteskala  " },
			{ "Tcmd", "ein. Die Attribute k�nnen nach ihrer relativen Bedeutung " },
			{ "itw", "gewichtet werden." },
			{ "rycs", "als Auswahlkriterien." },
			{ "Ipdsm", "\" Ideal point\" Entscheidungshilfe" },
			{ "Rsawcw", "Sensitivit�tsanalyse mit aktuellen Gewichtungen starten ..." },
			{ "Make_decision", "Entscheidung treffen" },
			{ "sap", "Sensitivit�tsanalyse-Parameter" }, //
			{ "vitr", "�berpr�ft IF-THEN Regeln" }, // Rule Validator
			{ "Scaatt", "W�hlen Sie Bedingungsattribut(e) und das Zielattribut der Regel" },
			{ "itrn", "IF-THEN Regel N " },
			{ " Validation", " �berpr�fung" },
			{ "Focal points: ", "Focal Punkte: " },
			{ "Dynamic update", "st�ndig aktualisieren" },
			{ "Rule text", "Regeltext" },
			{ "No", "Keine" },
			{ "Left", "Links" },
			{ "Right", "Rechts" },
			{ "Both", "Beide" },
			{ "Cspw", "Conditions scatter-plot window" },
			{ "support", "unterst�tzen" },
			{ "do_not_support", "nicht unterst�tzen" },
			{ "not_relevant", "nicht relevant" },
			{ "contradict", "widersprechen" },
			{ "sup", "support (quality in respect to the conditions)" },
			{ "cov", "coverage (quality in respect to the target)" }, //RuleValidator
			{ "Sias", "�hnlichkeit im Attribut-Raum" }, //SimilarityCalc

			{ "Auic", "In den Berechnungen verwendete Attribute:" },
			{ "Continue", "Weiter" },
			{ "Distance_to ", "Entfernung zu " },
			{ "Htctd", "Wie soll die Distanz zur Gruppe berechnet werden ?" },
			{ "Dttmc", "Distanz zum Massenzentrum der Gruppe" },
			{ "Mdtgm", "Minimaldistanz zu Gruppenmitgliedern" },
			{ "Adtgm", "Mittlere Distanz zu Gruppenmitgliedern" },
			{ "Metric:", "Metrik:" },
			{ "Robj", "Referenzobjekt(e)" },
			//SimilarityCalc
			{ "Cbs", "Klassifizierung nach �hnlichkeit" }, // SimilarityClassCalc
			{ "Sfcs", "Beispiel(e) f�r erste Klasse w�hlen" },
			{ "fcs", "Beispiele f�r erste Klasse:" },
			{ "S2cs", "Beispiel(e) f�r zweite Klasse w�hlen" },
			{ "Classification: ", "Klassifizierung: " },
			{ "Htctdttg", "Wie soll die Distanz zur Gruppe berechnet werden ?" },
			{ "Dttmcotg", "Distanz zum Massenzentrum der Gruppe" },
			{ "Dtfc", "Distanzklassengrenzen:" }, //SimilarityClassCalc
			{ "Set_equal_weights", "gleiche Gewichtung" },
			{ "YCAAM", "Sie k�nnen jederzeit weitere Kriterien w�hlen (drop-down Menu) " },
			{ "Ycara", "Sie k�nnen die einzelnen Kriterien jederzeit entfernen (drop-down Menu) " },
			{ "Add_criterion", "Kriterium hinzuf�gen" },
			{ "Remove_criterion", "Kriterium entfernen" },
			{ "Srob", "Referenzobjekt(e) ausw�hlen" },
			{ "Chtocc", "Hier klicken um Farbe zu �ndern" },
			{ "Costtbm", "Kosten- (zu minimieren) und Profit- (zu maximieren) kriterien werden hier unterschieden. " + "Klicken Sie auf den Pfeil um Kriterientyp zu �ndern" },
			{ "Ustcw", "Benutzen Sie den Regler um die Gewichtung des Attributs zu �ndern" }, //WAPanel
			{ "percentage", "Prozent" }, { "ratio", "Verh�ltnis" }, { "sel_attr", "Selektierte Attribute:" }, { "div_by", "Geteilt durch:" }, { "another_attribute", "weiteres Attribute:" }, { "a_constant", "eine Konstante:" },
			{ "compute", "Berechnung:" }, { "_in_", " in " }, { "_of_", " von " }, { "Rule_N_", "Regel N " }, { "_of", "% von" }, { "IF_", "WENN:" }, { "THEN_", "DANN:" },
			{ "attributes_by_values1", "attributes by values of another selected attribute, or by the sum " }, { "of_values", "of values " }, { "of_these_attributes1", "of these attributes, or by a fixed number. Suitable for calculation " },
			{ "of", "von " }, { "to_be_divided_by1", "to be divided by another attribute (to be selected later on), or " }, { "by_the", "by the " }, { "sum_of_these1", "sum of these attributes, or by a fixed number (to be selected later " },
			{ "on_", "on)." }, { "Average", "Durchsschnitt" }, { "Variance:", "Abweichung: " }, { "Weighted_average", "Gewichtetes Mittel" }, { "Decrease", "Absteigender" }, { "Increase", "Aufsteigender" }, { "order", " Ordnung" },
			{ "Criterion_weight ", "Gewichtskriterium" }, { "Samples", "Stichproben" }, { "Like ", "Wie " }, { "Non_classified", "Nicht klassifiziert" }, { "Distance_to ", "Distanz zu " }, { "PS", "Pareto Satz Rechner" },
			{ "PS_expl", "Baut den Satz der nicht-dominierende Optionen" }, { "PS_empty", "Pareto Satz ist leer" }, { "Tolerance", "Toleranz" }, { "Def_PS", "Definition des Pareto Satzes:" },
			{ "Comp_by_VG", "Berechnen nach Methode von Prof. V.Gitis" }, { "debug", "debuggen" }, { "equivalent", "gleichwertig" }, { "better", "bessere" }, { "worse", "schlechter" }, { "incomparable", "unvergleichlich" },
			{ "MCC_expl", "Klassifiziert der Optionen in Beziehung zur eine ausgew�hlte" }, { "MCC", "Multi-Kriterien Vergleich" }, { "Ref_val_of_criteria", "Referenz Werte der Kriterien:" }, { "Sync_Rel_Val", "Relative Werte Synchronisieren" },
			{ "Roptions", "Referenz Option(en)" }, { "best", "Beste" }, { "worst", "Schlechtest" }, { "Compare to", "Vergleich zu" }, { "values", "Werte" }, { "from", "von" }, { "no_param_corresp", "No correspondence between parameters!" },
			{ "The_attribute", "The attribute" }, { "dep_on_several_params", "depends on several parameters" },
			{ "Please_indicate", "Please indicate which of the parameters are subject to " + "the aggregation and which of them must remain variable:" }, { "aggregate", "aggregate" }, { "vary", "vary" }, { "Values", "Values" },
			{ "Indicate_var_par", "Indicate varying parameters" }, { "Nothing_to_aggregate", "Nothing to aggregate!" }, { "Aggregate_at_least_one", "Please select at least one parameter to be subject to aggregation!" },
			{ "attr_not_specified", "The attribute to divide by is not specified!" }, { "ill_divide_value", "Illegal value to divide by!" }, { "too_many_attributes", "Too many attributes selected!" },
			{ "select_one_with_many_params", "Select a single attribute depending on two or more parameters." }, { "total", "Gesamtsumme" }, { "calc_in_progress", "Calculation in progress" }, { "calc_finished", "Calculation finished!" },
			{ "Computes_percentiles", "Computes percentiles from multiple attributes in each " + "row of the table" }, { "Select_attr_for_percentiles", "Select a group of numeric attributes for " + "the computation of percentiles." },
			{ "Specify_percentiles", "Specify the percentiles (from 0 to 100) to be computed:" }, { "Percentiles", "Percentiles" }, { "No_percentiles", "No percentile values given!" }, { "Illegal_percentile", "Illegal percentile value" },
			{ "percentile_of", "percentile of" }, { "Example", "Beispiel" }, { "single_param_dep_attr_selected", "You have selected a single " + "parameter-dependent attribute." }, { "how_to_use", "How do you intend to use it in the formula?" },
			{ "attr_whole1", "The attribute as a whole is an element of the formula." }, { "attr_whole2", "The result will be an attribute depending on the same " + "parameters." },
			{ "indiv_columns1", "individual columns belonging to the attribute are " + "elements of the formula." }, { "indiv_columns2", "The result will be a parameter-independent attribute." }, { "par_dep_attr", "Parameter-dependent attribute" },
			{ "show_on_map", "Show computation results on map" }, { "want_show_on_map", "Do you wish the computation results to be represented on a map?" }, { "main_map", "Show the results on the map in the main window" },
			{ "new_map", "Show the results in a new map window" }, { "no_map", "Do not show the results on a map" }, { "failed_make_map", "Failed to construct a new map window!" }, { "window_name", "Window name" } };

	public Object[][] getContents() {
		return contents;
	}
}