package spade.vis.event;

import java.util.EventListener;

/**
* EventReceiver is a generic interface to be implemented by objects that
* are interested to receive events generated by some other objects.
* Events are differentiated by their identifiers, e.g. "MouseMove" or
* "ObjectSelect".
*/

public interface EventReceiver extends EventListener {
	/**
	* The EventReceiver answers whether it is interested in getting the specified
	* kind of events.
	*/
	public boolean doesListenToEvent(String eventId);

	/**
	* This method is used for delivering events to the Event Receiver.
	*/
	public void eventOccurred(DEvent evt);

	/**
	* Returns a unique identifier of the event receiver (may be produced
	* automatically, used only internally, not shown to the user).
	*/
	public String getIdentifier();
}