alter table flickr_europe 
drop column region_320000_id;
alter table flickr_europe 
drop column region_160000_id;
alter table flickr_europe 
drop column region_80000_id;
alter table flickr_europe 
drop column region_40000_id;
alter table flickr_europe 
drop column region_20000_id;
alter table flickr_europe 
drop column region_10000_id;
alter table flickr_europe 
drop column region_5000_id;
alter table flickr_europe 
drop column region_2500_id;
alter table flickr_europe 
drop column region_1250_id;
alter table flickr_europe 
drop column region_750_id;
alter table flickr_europe 
drop column region_375_id;
alter table flickr_europe 
drop column region_checked;