  CREATE TABLE "STICHSTRASSEN_NAME"
   (  "ID" NUMBER(38,0),
  "X" VARCHAR2(40),
  "Y" VARCHAR2(40),
  "CNT" NUMBER(38,0)
   );

  CREATE TABLE "STICHSTRASSEN"
   (  "ID" NUMBER(38,0),
  "X" VARCHAR2(40),
  "Y" VARCHAR2(40),
  "CNT" NUMBER(38,0)
   );


  CREATE TABLE "STADT_VOLLST"
   (  "GKZ" VARCHAR2(8),
  "STADTNAME" VARCHAR2(100),
  "NAV_ZO_OBJEKT" NUMBER,
  "NAV_ALL_OBJEKT" NUMBER,
  "P_OBJEKT" NUMBER,
  "DIFF_OBJEKT" NUMBER,
  "QUALI_OBJEKT" NUMBER,
  "NAV_ALL_NAME" NUMBER,
  "NAV_NONAME" NUMBER,
  "P_NAME" NUMBER,
  "DIFF_NAME" NUMBER,
  "QUALI_NAME" NUMBER,
  "NAV_EB_10" NUMBER,
  "NAV_ALL_EB10" NUMBER,
  "P_EB_10" NUMBER,
  "DIFF_EB_10" NUMBER,
  "QUALI_EB10" NUMBER,
  "NAV_EB_3" NUMBER,
  "NAV_ALL_EB3" NUMBER,
  "PROZENT" NUMBER,
  "DIFF_EB3" NUMBER,
  "QUALI_EB3" NUMBER,
  "NAV_FW" NUMBER,
  "NAV_ALL_FW" NUMBER,
  "P_FW_ALL" NUMBER,
  "DIFF_FW_ALL" NUMBER,
  "QUALI_FW10" NUMBER,
  "NAV_FW3" NUMBER,
  "NAV_ALL_FW3" NUMBER,
  "P_FW3" NUMBER,
  "DIFF_FW3" NUMBER,
  "QUALI_FW3" NUMBER,
  "NAV_FZ" NUMBER,
  "NAV_ALL_FZ10" NUMBER,
  "P_FZ10" NUMBER,
  "DIFF_FZ_10" NUMBER,
  "QUALI_FZ10" NUMBER,
  "NAV_FZ3" NUMBER,
  "NAV_ALL_FZ3" NUMBER,
  "P_FZ3" NUMBER,
  "DIFF_FZ3" NUMBER,
  "QUALI_FZ3" NUMBER,
  "NAV_KMH10" NUMBER,
  "NAV_ALL_KMH10" NUMBER,
  "P_KMH10" NUMBER,
  "DIFF_KMH10" NUMBER,
  "QUALI_KMH10" NUMBER,
  "NAV_KMH3" NUMBER,
  "NAV_ALL_KMH3" NUMBER,
  "P_KMH3" NUMBER,
  "DIFF_KMH3" NUMBER,
  "QUALI_KMH3" NUMBER
   );

  CREATE TABLE "PLANET_OSM_LINE_NEW"
   (  "NR" NUMBER,
  "OSM_ID" NUMBER,
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "JUNCTION" VARCHAR2(15),
  "ROUTE" VARCHAR2(80),
  "ACCESS_" VARCHAR2(38),
  "WAY" "MDSYS"."SDO_GEOMETRY" ,
  "LAENGE_FULL_OSM" NUMBER
   );

  CREATE TABLE "NAV_D_ENDPOINTS1"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "X0" VARCHAR2(40),
  "Y0" VARCHAR2(40),
  "X1" VARCHAR2(40),
  "Y1" VARCHAR2(40)
   );

  CREATE TABLE "NAV_D_BP"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "NAV_D_ALL_ENDPOINTS"
   (  "ID" NUMBER(10,0),
  "PRIM_NAME" VARCHAR2(117),
  "X0" VARCHAR2(40),
  "Y0" VARCHAR2(40),
  "X1" VARCHAR2(40),
  "Y1" VARCHAR2(40)
   );

  CREATE TABLE "NAV_D_ALL"
   (  "ID" NUMBER(10,0),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(4000),
  "KAT" VARCHAR2(1),
  "LAENGE" NUMBER,
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "NAV_D"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "MAIKE_VOLLSTAENDIGKEIT_KREISE"
   (  "KKZ" VARCHAR2(20),
  "KREISNAME" CHAR(33),
  "NAV_ZO" NUMBER,
  "NAV_ALL" NUMBER,
  "PROZENT" NUMBER
   );


  CREATE TABLE "MAIKE_OSM"
   (  "NR" NUMBER,
  "OSM_ID" NUMBER,
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "JUNCTION" VARCHAR2(15),
  "ROUTE" VARCHAR2(80),
  "ACCESS_" VARCHAR2(38),
  "WAY" "MDSYS"."SDO_GEOMETRY" ,
  "LAENGE_FULL_OSM" NUMBER
   );

  CREATE TABLE "MAIKE_NAV"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "FL_DTOK_BONN_OSM"
   (  "X" FLOAT(126),
  "Y" FLOAT(126),
  "DATETIME" DATE,
  "NR" NUMBER,
  "OSM_ID" NUMBER,
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "JUNCTION" VARCHAR2(15),
  "ROUTE" VARCHAR2(80),
  "ACCESS_" VARCHAR2(38),
  "WAY" "MDSYS"."SDO_GEOMETRY" ,
  "LAENGE_FULL_OSM" NUMBER
   );

  CREATE TABLE "D_ZUORDNUNG_ALLPOSDIFF"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "ORT" VARCHAR2(6),
  "POSDIFF" NUMBER
   );


  CREATE TABLE "D_ZUORDNUNG_ALLKMH"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "ORT" VARCHAR2(6),
  "KMH_OSM" NUMBER,
  "KMH_NAV" NUMBER,
  "DIFF" NUMBER
   );

  CREATE TABLE "D_ZUORDNUNG_ALL"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "ORT" VARCHAR2(6)
   );

  CREATE TABLE "D_ZUORDNUNGBP"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "KAT" VARCHAR2(1),
  "RANG" NUMBER
   );

  CREATE TABLE "D_ZO_KKZ"
   (  "KKZ" VARCHAR2(20),
  "OSMCT" NUMBER,
  "NAVCT" NUMBER
   );

  CREATE TABLE "D_ZO_ATTR"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER
   );

  CREATE TABLE "D_STICHSTRASSEN"
   (  "ID" NUMBER(38,0),
  "X" VARCHAR2(40),
  "Y" VARCHAR2(40),
  "CNT" NUMBER(38,0)
   );


  CREATE TABLE "D_STADT_VOLLST_NEU"
   (  "GKZ" VARCHAR2(8),
  "STADTNAME" VARCHAR2(100),
  "NAV_ZO_OBJEKT" NUMBER,
  "NAV_ALL_OBJEKT" NUMBER,
  "P_OBJEKT" NUMBER,
  "DIFF_OBJEKT" NUMBER,
  "QUALI_OBJEKT" NUMBER,
  "NAV_ALL_NAME" NUMBER,
  "NAV_NONAME" NUMBER,
  "P_NAME" NUMBER,
  "DIFF_NAME" NUMBER,
  "QUALI_NAME" NUMBER,
  "NAV_EB_10" NUMBER,
  "NAV_ALL_EB10" NUMBER,
  "P_EB_10" NUMBER,
  "DIFF_EB_10" NUMBER,
  "QUALI_EB10" NUMBER,
  "NAV_EB_3" NUMBER,
  "NAV_ALL_EB3" NUMBER,
  "PROZENT" NUMBER,
  "DIFF_EB3" NUMBER,
  "QUALI_EB3" NUMBER,
  "NAV_FW" NUMBER,
  "NAV_ALL_FW" NUMBER,
  "P_FW_ALL" NUMBER,
  "DIFF_FW_ALL" NUMBER,
  "QUALI_FW10" NUMBER,
  "NAV_FW3" NUMBER,
  "NAV_ALL_FW3" NUMBER,
  "P_FW3" NUMBER,
  "DIFF_FW3" NUMBER,
  "QUALI_FW3" NUMBER,
  "NAV_FZ" NUMBER,
  "NAV_ALL_FZ10" NUMBER,
  "P_FZ10" NUMBER,
  "DIFF_FZ_10" NUMBER,
  "QUALI_FZ10" NUMBER,
  "NAV_FZ3" NUMBER,
  "NAV_ALL_FZ3" NUMBER,
  "P_FZ3" NUMBER,
  "DIFF_FZ3" NUMBER,
  "QUALI_FZ3" NUMBER,
  "NAV_KMH10" NUMBER,
  "NAV_ALL_KMH10" NUMBER,
  "P_KMH10" NUMBER,
  "DIFF_KMH10" NUMBER,
  "QUALI_KMH10" NUMBER,
  "NAV_KMH3" NUMBER,
  "NAV_ALL_KMH3" NUMBER,
  "P_KMH3" NUMBER,
  "DIFF_KMH3" NUMBER,
  "QUALI_KMH3" NUMBER,
  "EW_QKM" NUMBER(5,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "MI_STYLE" VARCHAR2(254),
  "NAV_DIFFKMH" NUMBER,
  "NAV_DIFFKMHALL" NUMBER,
  "P_KMHATTRDIFF" NUMBER
   );

  CREATE TABLE "D_STADT_VOLLST"
   (  "GKZ" VARCHAR2(8),
  "STADTNAME" VARCHAR2(100),
  "NAV_ZO_OBJEKT" NUMBER,
  "NAV_ALL_OBJEKT" NUMBER,
  "P_OBJEKT" NUMBER,
  "DIFF_OBJEKT" NUMBER,
  "QUALI_OBJEKT" NUMBER,
  "NAV_ALL_NAME" NUMBER,
  "NAV_NONAME" NUMBER,
  "P_NAME" NUMBER,
  "DIFF_NAME" NUMBER,
  "QUALI_NAME" NUMBER,
  "NAV_EB_10" NUMBER,
  "NAV_ALL_EB10" NUMBER,
  "P_EB_10" NUMBER,
  "DIFF_EB_10" NUMBER,
  "QUALI_EB10" NUMBER,
  "NAV_EB_3" NUMBER,
  "NAV_ALL_EB3" NUMBER,
  "PROZENT" NUMBER,
  "DIFF_EB3" NUMBER,
  "QUALI_EB3" NUMBER,
  "NAV_FW" NUMBER,
  "NAV_ALL_FW" NUMBER,
  "P_FW_ALL" NUMBER,
  "DIFF_FW_ALL" NUMBER,
  "QUALI_FW10" NUMBER,
  "NAV_FW3" NUMBER,
  "NAV_ALL_FW3" NUMBER,
  "P_FW3" NUMBER,
  "DIFF_FW3" NUMBER,
  "QUALI_FW3" NUMBER,
  "NAV_FZ" NUMBER,
  "NAV_ALL_FZ10" NUMBER,
  "P_FZ10" NUMBER,
  "DIFF_FZ_10" NUMBER,
  "QUALI_FZ10" NUMBER,
  "NAV_FZ3" NUMBER,
  "NAV_ALL_FZ3" NUMBER,
  "P_FZ3" NUMBER,
  "DIFF_FZ3" NUMBER,
  "QUALI_FZ3" NUMBER,
  "NAV_KMH10" NUMBER,
  "NAV_ALL_KMH10" NUMBER,
  "P_KMH10" NUMBER,
  "DIFF_KMH10" NUMBER,
  "QUALI_KMH10" NUMBER,
  "NAV_KMH3" NUMBER,
  "NAV_ALL_KMH3" NUMBER,
  "P_KMH3" NUMBER,
  "DIFF_KMH3" NUMBER,
  "QUALI_KMH3" NUMBER,
  "GKZ_NEU" VARCHAR2(8),
  "EW_QKM" NUMBER(5,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "MI_STYLE" VARCHAR2(254)
   );


  CREATE TABLE "D_STADT_DIFFKMH"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "NAV_DIFF" NUMBER,
  "NAV_ALL" NUMBER,
  "DIFF_PROZ" NUMBER
   );

  CREATE TABLE "D_SIEDLUNG_BUFF10"
   (  "NAME" VARCHAR2(40),
  "GEO_OBJECT" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_SIEDLUNG_BUFF"
   (  "NAME" VARCHAR2(40),
  "GEO_OBJECT" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_SIEDLUNG_BP"
   (  "NAME" VARCHAR2(40),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254)
   );

  CREATE TABLE "D_SIEDLUNG"
   (  "NAME" VARCHAR2(40),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254)
   );

  CREATE TABLE "D_RANGKAT"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "RANG" NUMBER
   );

  CREATE TABLE "D_RANG"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "KAT" VARCHAR2(1),
  "RANG" NUMBER
   );

  CREATE TABLE "D_QUALIALL"
   (  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "M30" CHAR(3),
  "M10" VARCHAR2(7),
  "M5" VARCHAR2(6)
   );

  CREATE TABLE "D_QUALI5"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "M5" VARCHAR2(6)
   );

  CREATE TABLE "D_QUALI30"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "M30" CHAR(3)
   );

  CREATE TABLE "D_QUALI10"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "M10" VARCHAR2(7)
   );

  CREATE TABLE "D_POSDIFF_NRW"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "ZO_5M" NUMBER,
  "ZO_10M" NUMBER,
  "ZO_ALL" NUMBER,
  "PROZENT_5" NUMBER,
  "PROZENT_10" NUMBER,
  "NAME" VARCHAR2(50),
  "TYP" NUMBER(5,0),
  "EW" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "BL" VARCHAR2(8)
   );

  CREATE TABLE "D_OSM_SIEDLUNG"
   (  "OSM_ID" NUMBER,
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NOGKZSTREETS"
   (  "NAME" VARCHAR2(50),
  "HAUPTSTADT" VARCHAR2(15),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "LKZ" VARCHAR2(8),
  "GKZ_NOMATCH" NUMBER,
  "GKZ_ALL" NUMBER,
  "PROZENT" NUMBER
   );

  CREATE TABLE "D_NAV_STICHSTRASSEN"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAV_SIEDLUNG_STICH_OLD"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_SIEDLUNG_STICH_2"
   (  "ID" NUMBER(10,0),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(4000),
  "KAT" VARCHAR2(1),
  "LAENGE" NUMBER,
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_SIEDLUNG_STICH"
   (  "ID" NUMBER(10,0),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(4000),
  "KAT" VARCHAR2(1),
  "LAENGE" NUMBER,
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_SIEDLUNG_AUSSORT"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_SIEDLUNG"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_NOTINBUFF10_S_OLD"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAV_NOTINBUFF10_STICH"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAV_NOTINBUFF10_AUSSORT1"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "SIEDLUNGNAME" VARCHAR2(40)
   );

  CREATE TABLE "D_NAV_NOTINBUFF10_AUSSORT"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAV_NOTINBUFF10"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "D_NAV_NOTINBUFF"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_PRINX" NUMBER,
  "MI_STYLE" VARCHAR2(254)
   );

  CREATE TABLE "D_NAV_HD"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAV_AUSSORT"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_NAVALL"
   (  "KKZ" VARCHAR2(20),
  "NAVALL" NUMBER
   );

  CREATE TABLE "D_NAV"
   (  "ID" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "GKZ" VARCHAR2(8),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_LAND"
   (  "LKZ" VARCHAR2(2),
  "NAME" VARCHAR2(50),
  "HAUPTSTADT" VARCHAR2(15),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254)
   );

  CREATE TABLE "D_K_OSM"
   (  "OSM_ID" NUMBER,
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_KREISE"
   (  "KKZ" VARCHAR2(5),
  "NAME" VARCHAR2(50),
  "SITZ" VARCHAR2(30),
  "TYP" NUMBER(5,0),
  "EW" NUMBER(10,0),
  "EW_M" NUMBER(10,0),
  "EW_W" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "AUSL" NUMBER(10,0),
  "HH" NUMBER(10,0),
  "EW_HH" NUMBER,
  "FZGE_GES" NUMBER(10,0),
  "KK_KAT" NUMBER(5,0),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254)
   );

  CREATE TABLE "D_KKZ_PROZENT"
   (  "KKZ" VARCHAR2(5),
  "NAME" VARCHAR2(50),
  "SITZ" VARCHAR2(30),
  "TYP" NUMBER(5,0),
  "EW" NUMBER(10,0),
  "EW_M" NUMBER(10,0),
  "EW_W" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "AUSL" NUMBER(10,0),
  "HH" NUMBER(10,0),
  "EW_HH" NUMBER,
  "FZGE_GES" NUMBER(10,0),
  "KK_KAT" NUMBER(5,0),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254),
  "OSMCT" NUMBER,
  "NAVCT" NUMBER,
  "NAVALL" NUMBER,
  "PROZENT" NUMBER
   );

  CREATE TABLE "D_GROSSSTADT"
   (  "STADTNAME" VARCHAR2(50),
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "ORT" VARCHAR2(6)
   );

  CREATE TABLE "D_GKZ_PROZENT"
   (  "GKZ" VARCHAR2(8),
  "NAME" VARCHAR2(50),
  "TYP" NUMBER(5,0),
  "GEMFREI" VARCHAR2(2),
  "EW" NUMBER(10,0),
  "EW_M" NUMBER(10,0),
  "EW_W" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "AUSL" NUMBER(10,0),
  "HH" NUMBER(10,0),
  "EW_HH" NUMBER,
  "FZGE_GES" NUMBER(10,0),
  "KK_KAT" NUMBER(5,0),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254),
  "NAV_ALL" NUMBER,
  "NAV_ZO" NUMBER,
  "PROZENT" NUMBER
   );

  CREATE TABLE "D_GKZ_POSDIFF3"
   (  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "ZO_5M" NUMBER,
  "ZO_10M" NUMBER,
  "ZO_ALL" NUMBER,
  "PROZENT_5" NUMBER,
  "PROZENT_10" NUMBER,
  "NAME" VARCHAR2(50),
  "TYP" NUMBER(5,0),
  "EW" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_GKZ_EB_NAV"
   (  "EW_QKM" NUMBER(5,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "R_NAV_ALL" NUMBER,
  "R_NAV" NUMBER,
  "PROZENT" NUMBER,
  "BL" VARCHAR2(8)
   );

  CREATE TABLE "D_GKZ_EB2"
   (  "EW_QKM" NUMBER(5,0),
  "NAME" VARCHAR2(50),
  "EW" NUMBER(10,0),
  "TYP" NUMBER(5,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "R_NAV_ALL" NUMBER,
  "R_NAV" NUMBER,
  "PROZENT" NUMBER
   );

  CREATE TABLE "D_GKZ_EB13"
   (  "NAME" VARCHAR2(50),
  "EW" NUMBER(10,0),
  "TYP" NUMBER(5,0),
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "R_NAV_ALL" NUMBER,
  "R_NAV" NUMBER,
  "PROZENT" NUMBER
   );


  CREATE TABLE "D_GKZ"
   (  "GKZ" VARCHAR2(8),
  "NAME" VARCHAR2(50),
  "TYP" NUMBER(5,0),
  "GEMFREI" VARCHAR2(2),
  "EW" NUMBER(10,0),
  "EW_M" NUMBER(10,0),
  "EW_W" NUMBER(10,0),
  "EW_QKM" NUMBER(5,0),
  "QKM" NUMBER,
  "AUSL" NUMBER(10,0),
  "HH" NUMBER(10,0),
  "EW_HH" NUMBER,
  "FZGE_GES" NUMBER(10,0),
  "KK_KAT" NUMBER(5,0),
  "MI_PRINX" NUMBER(10,0) NOT NULL ENABLE,
  "GEOLOC" "MDSYS"."SDO_GEOMETRY" ,
  "MI_STYLE" VARCHAR2(254)
   );


  CREATE TABLE "D_CUT_OSM30"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "D_CUT_OSM10"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "D_CUT_OSM"
   (  "OSM_ID" NUMBER(38,0),
  "NAV_ID" NUMBER(38,0),
  "OSM_NAME" VARCHAR2(255),
  "OSM_NAME2" VARCHAR2(255),
  "NAV_NAME" VARCHAR2(255),
  "NAV_NAME2" VARCHAR2(255),
  "NAV_LAENGE" NUMBER,
  "OSM_SEGLAENGE" NUMBER,
  "LS1" NUMBER(38,0),
  "LS2" NUMBER(38,0),
  "LS3" NUMBER(38,0),
  "LS4" NUMBER(38,0),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );


  CREATE TABLE "D_BUFF5"
   (  "ID" NUMBER,
  "KAT" VARCHAR2(1),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSSWEG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "KM_H" NUMBER,
  "X" FLOAT(126),
  "Y" FLOAT(126),
  "GEO_OBJECT" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_BUFF30"
   (  "ID" NUMBER,
  "KAT" VARCHAR2(1),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSSWEG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "KM_H" NUMBER,
  "X" FLOAT(126),
  "Y" FLOAT(126),
  "GEO_OBJECT" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "D_BUFF10"
   (  "ID" NUMBER,
  "KAT" VARCHAR2(1),
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSSWEG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "KM_H" NUMBER,
  "X" FLOAT(126),
  "Y" FLOAT(126),
  "GEO_OBJECT" "MDSYS"."SDO_GEOMETRY"
   );

  CREATE TABLE "BONN_RANG"
   (  "STADTNAME" VARCHAR2(50),
  "GKZ" VARCHAR2(8) NOT NULL ENABLE,
  "RANG" NUMBER,
  "NAV_ID" NUMBER(38,0),
  "OSM_ID" NUMBER(38,0),
  "HIGHWAY" VARCHAR2(14),
  "NAME" VARCHAR2(152),
  "REF_" VARCHAR2(56),
  "ONEWAY" VARCHAR2(34),
  "FOOT" VARCHAR2(49),
  "MAXSPEED" NUMBER,
  "ACCESS_" VARCHAR2(38),
  "LAENGE_FULL_OSM" NUMBER,
  "PRIM_NAME" VARCHAR2(117),
  "SEK_NAME" VARCHAR2(117),
  "KAT" VARCHAR2(1),
  "LAENGE" FLOAT(126),
  "RICHTUNG" NUMBER,
  "FUSS_ZONE" NUMBER,
  "FUSSWEG" NUMBER,
  "KM_H" NUMBER,
  "ORT" VARCHAR2(6),
  "GEOLOC" "MDSYS"."SDO_GEOMETRY"
   );