package ui;


public class Res extends java.util.ListResourceBundle {
	static final Object[][] contents = new String[][] { { "Select_the_table_for", "Select the table for adding an attribute" }, { "Type", "Type" }, { "Integer", "Integer" }, { "Real", "Real" }, { "String", "String" },
			{ "Default_value", "Default value" }, { "Specify_a_new", "Specify a new attribute" }, { "added_to_the_table", " added to the table" }, { "Attribute", "Attribute " }, { "The_attribute_is", "The attribute is stored in file " },
			{ "Attributes", "Attributes" }, { "include_non_numeric", "include non-numeric attributes" }, { "Selected_attributes_", "Selected attributes:" }, { "Selected_attribute_", "Selected attribute:" }, { "Clear_list", "Clear list" },
			{ "No_attributes", "No attributes selected!" }, { "At_least", "At least " }, { "Exactly", "Exactly " }, { "attributes_must_be", " attributes must be selected!" }, { "No_more_than", "No more than " },
			{ "No_values_of_the", "No values of the attribute found in the data!" }, { "All_values_of_the", "All values of the attribute are the same!" }, { "No_calculations", "No calculations available!" },
			{ "Select_the_table_for1", "Select the table for calculation" }, { "Select_attribute_s", "Select attribute(s) for calculations" }, { "is_not", " is not " }, { "The_method", "The method " },
			{ "applicable_to_the", "applicable to the selected attributes!" }, { "Calculate", "Calculate" }, { "Table", "Table \u0000" }, { "No_tables_or_layers", "No tables or layers loaded yet!" },
			{ "Specify_the_dataset", "Specify the dataset to reload:" }, { "Reload_data", "Reload data" }, { "The_data_have_been", "The data have been reloaded" }, { "File", "File" }, { "Load_project", "Load project" },
			{ "Load_data_", "Load data ..." }, { "Reload_data_", "Reload data ..." }, { "Save_project", "Save project" }, { "Export_data", "Export data" }, { "Store_data_from_a", "Store data from a table" }, { "Add_attribute", "Add attribute" },
			{ "Remove_table", "Remove table" }, { "Join_tables", "Join tables" }, { "Remove_map_layer", "Remove map layer" }, { "Remove_map", "Remove map" }, { "Remove_all_data", "Remove all data" }, { "Quit", "Quit" }, { "Display", "Display" },
			{ "Display_wizard_", "Display wizard ..." }, { "View_table", "View table" }, { "Clean_the_map", "Clean the map" }, { "Another_window", "Another window" }, { "Calculate_in_a_table", "Calculate in a table" },
			{ "Geographic", "Geographic computations" }, { "Tools", "Tools" }, { "Options", "Options" }, { "Show_records_options_", "Show records options..." }, { "Verify_relationships", "Verify relationships between variables" },
			{ "Warn_of_misuse", "Warn of misuse" }, { "Help", "Help" }, { "Index", "Index" }, { "Decision_support", "Decision support" }, { "About", "About" }, { "About_project", "About project" }, { "Data_Server_URL_", "Data Server URL:" },
			{ "Data_Server_URL", "Data Server URL" }, { "Select_the_file_with", "Select the file with project description" }, { "Select_project_", "Select project:" }, { "Select_project", "Select project" },
			{ "Could_not_open_the", "Could not open the stream: " }, { "Server_error_", "Server error: " }, { "The_directory_for", "The directory for storing data is not specified" },
			{ "The_script_to_use_for", "The script to use for storing data is not specified" }, { "What_table_to_remove_", "What table to remove?" }, { "Confirm", "Confirm" }, { "Remove_the_table", "Remove the table " },
			{ "What_layer_to_remove_", "What layer to remove?" }, { "remove_the_related", "remove the related table" }, { "Remove_the_layer", "Remove the layer " }, { "and_the_related_table", " and the related table?" },
			{ "Remove_the_current", "Remove the current map?" }, { "Remove_all_the_data_", "Remove all the data?" }, { "Select_the_table_for2", "Select the table for viewing" }, { "Select_the_table", "Select the table" },
			{ "Select_table_or_layer", "Select a table or a map layer" }, { "tables", "Tables" }, { "layers", "Layers" }, { "Record_viewing", "Record viewing options" }, { "Select_the_layers_to", "Select the layers to clean" },
			{ "Select_attributes", "Select attributes" }, { "Select_the_table_for3", "Select the table for visualisation" }, { "Select_attribute_s_to", "Select attribute(s) to visualise" }, { "Maps", "Maps" },
			{ "Do_not_build_a_map", "Do not build a map" }, { "Charts", "Charts" }, { "Do_not_build_a_chart", "Do not build a chart" }, { "Select_display_type", "Select display type" },
			{ "Select_the_layer_to", "Select the layer to link to the table" }, { "Currently_displayed", "Currently displayed" }, { "Clear_all", " Clear all" }, { "Select_all", "Select all" }, { "Click_here_to_get", "Click here to get help" },
			{ "You_can_enable_popup", "You can enable popup displays for interactive access to data records" }, { "You_can_use_separate", "You can use separate window as additional display for data record " + "showing purposes" },
			{ "When_this_is_switched", "When this is switched ON you can see the latest data output in Show " + "Record window" },
			{ "You_can_set_limit_of", "You can set limit of lines used to show data records in popup and " + "Show Record window" }, { "Select_all_attributes", "Select all attributes and add them to Show Record window" },
			{ "Deselect_all", "Deselect all previously selected attributes and remove them from " + "Show Record window" }, { "Set_attributes_showed", "Set attributes showed on all data displays as current selection" },
			{ "When_switched_ON_new", "When switched ON, new attributes are added automatically to the Show " + "Record window" },
			{ "When_switched_ON", "When switched ON, parental attributes are added automatically to " + "the Show Record window" }, { "Object_view", "Object view parameters" }, { "Enable_record_display", "Enable record display in popup window" },
			{ "Use_persistent_record", "Use persistent record view" }, { "Show_maximum", "Show maximum" }, { "lines", "lines" }, { "What_to_show_in_the", "What to show in the persistent view: " },
			{ "Attributes_on_all", "Attributes on all displays" }, { "Selection_from_list", "Selection from list" }, { "new_attributes_added", "new attributes added to displays" }, { "parents_of_derived", "parents of derived attributes" },
			{ "Automatically_add_", "Automatically add:" }, { "Pan_map_to_the_window", "Pan map to the window" }, { "Zoom_In", "Zoom In" }, { "Zoom_Out", "Zoom Out" }, { "Zoom_Undo", "Zoom Undo" }, { "Print", "Print" },
			{ "Save_map_to_file", "Save map to file" }, { "Drag_Zoom_In", "Drag:\nZoom In" }, { "Drag_Move_map", "Drag:\nMove map" }, { "Drag_Select_objects", "Drag:\nSelect objects" }, { "deselect", "Deselect all objects" }, { "West", "West" },
			{ "South_West", "South-West" }, { "South", "South" }, { "South_East", "South-East" }, { "East", "East" }, { "North_East", "North-East" }, { "North", "North" }, { "North_West", "North-West" }, { "Move_to_", "Move to:\n" },
			{ "Legend", "Legend" }, { "Select_what_to_print_", "Select what to print:" }, { "Map", "Map" }, { "Fit_to_minimum_page", "Fit to minimum page size" }, { "Option_", "Option:" }, { "Printing", "Printing" }, { "Print_Map", "Print Map" },
			{ "Printing_map_", "Printing map..." }, { "Printing_legend_", "Printing legend..." }, { "Printing_map_and_legend", "Printing map and legend..." },
			{ "Saving_graphics_into", "Saving graphics into a file is not included in" + " this version of the system" }, { "Saving", "Saving" }, { "This_format_is_not", "This format is not supported!" },
			{ "JPEG_image_encoding", "JPEG image encoding is not supported by Java 1.1.x!" + " Use Java 2 or higher." }, { "Saving_map_", "Saving map..." }, { "Select_the_file_to", "Select the file to save map" },
			{ "Saving_legend_", "Saving legend..." }, { "Select_the_file_to1", "Select the file to save legend" }, { "Select_the_table_to", "Select the table to export" }, { "Export_the_table_to", "Export the table to the file" },
			{ "Error_writing_to_the", "Error writing to the file: " }, { "The_directory_for1", "The directory for storing data is not specified!" }, { "The_CGI_script_for", "The CGI script for storing data is not specified!" },
			{ "Select_attributes_to", "Select attributes to store" }, { "Store_the_data_to_the", "Store the data to the file" }, { "Fit_to_the_window", "Fit to the window" }, { "Multiply_by", "Multiply by" }, { "Undo", "Undo" },
			{ "Manipulate", "Manipulate" }, { "Object_view1", "Object view" }, { "Save_or_print_map", "Save or print map" }, { "CommonGIS", "CommonGIS (formerly Descartes)" },
			{ "System_for", "System for Exploratory Analysis of Spatially Referenced Data" }, { "Version", "Version" }, { "debug_info", "Debug information" }, { "included", "included" }, { "excluded", "excluded" },
			{ "no_warranty_string", "This version of the software provided AS IS: no support can be claimed" }, { "copyright", "(c) Fraunhofer IAIS 1995-2010" }, { "e-mail", "e-mail gennady.andrienko@iais.fraunhofer.de" },
			{ "url", "http://www.CommonGIS.com/" }, { "development_supported_by_EU", "Development of the system was partly supported by EU" }, { "within_projects", "within funded projects" },
			{ "commongis_project", "CommonGIS (ESPRIT project 28983, 1998-2001)" }, { "spin_project", "SPIN (IST-1999-10536, 2000-2003)" }, { "GIMMI_project", "GIMMI (IST-2001-34245, 2002-2004)" }, { "and_", "and " },
			{ "commongis_project_url", "http://commongis.jrc.it/" }, { "spin_project_url", "http://www.ccg.leeds.ac.uk/spin/" }, { "GIMMI_project_url", "http://services.txt.it/gimmi/" },
			{ "third_parties_software", "The system includes software modules implemented by third parties:" }, { "iitp", "File management utilities by IITP RAS, http://www.iitp.ru/" },
			{ "uni_Bonn", "Reading OpenGIS simple feature specification by University of Bonn" }, { "uni_Bonn_url", "http://www.giub.uni-bonn.de/exse/results/welcome.html" }, { "Java_version_", "Java version " },
			{ "No_vis_methods_", "No visualisation methods appropriate for the individual maps!" }, { "Choose_vis_method_", "Choose the visualisation method for the individual maps:" }, { "together", "together" }, { "Select_layer", "Select layer" },
			{ "Table_join", "Table join" }, { "New_table_name", "New table name" }, { "Select_attributes_to_join", "Select attributes to join" }, { "Preparing_table_", "Preparing attributes " }, { "Calculating", "Joining: " }, { "_of_", " of " },
			{ "Done", "Done" }, { "All", "All" }, { "None", "None" }, { "Selected_attributes", "Selected attributes:\n" }, { "From_table", "\nFrom table " }, { "time_functions", "Time functions" }, { "no_attributes", "No attributes found!" },
			{ "no_params", "No parameters specified!" }, { "no_numeric_attributes", "No numeric attributes found!" }, { "time_dep", "depends on a temporal parameter" }, { "par_dep", "depends on a non-temporal parameter" },
			{ "no_par_dep_attr", "No parameter-dependent attributes found!" }, { "depends_on_1", "depends on a parameter." }, { "depends_on_2", "depends on parameters." }, { "depend_on_1", "depend on a parameter." },
			{ "depend_on_2", "depend on parameters." }, { "select_values_1", "Select values of the parameter" }, { "select_values_2", "Select values of each parameter" }, { "Some_chosen_attr", "Some of the attributes you have chosen" },
			{ "depend_on_params", "depend on parameters." }, { "select_values_3", "Select parameter values for each attribute" }, { "select_param_values", "Select parameter values" }, { "individually", "Consider each attribute individually" },
			{ "attribute_selected_", "The following attribute was selected:" }, { "attributes_selected_", "The following attributes were selected:" }, { "confirm_selection", "Confirm selection" }, { "time_analysis", "Time analysis" },
			{ "start_time_functions", "Do you wish to use time-series visualisation?" }, { "Failed_to_load_data", "Failed to load the data!" }, { "no_layers_with_data", "No layers with thematic data found!" },
			{ "no_tables_to_join", "No tables to join!" }, { "view_links", "Table-layer links" }, { "link", "Link" }, { "Select_a_layer", "Select a layer" }, { "Select_a_layer_to", "Select a layer to link to the table" },
			{ "The_table_has_been", "The table has been linked to layer " }, { "Choose", "Choose" }, { "More", "More" }, { "Choose_single", "Choose a single attribute" }, { "all_values", "all possible values" },
			{ "no_data_in_table", "No data found in the table!" }, { "window_name", "Window name" }, { "no_layers_with_2_tables", "No layers with 2 or more tables" }, { "Select_individual_attributes", "Select individual attributes" },
			{ "Select_tables_to_join", "Select tables to join" }, { "special_time_vis", "Special time-series visualisation?" },
			{ "ask_use_special_time_vis", "Do you wish to use one of the following " + "visualisation methods specially designed for time-series data?" }, { "other_vis_methods", "Other visualisation methods" }, { "reorder", "Reorder" },
			{ "reorder_attrs", "Reorder attributes" }, { "no_map_view", "No map view found!" }, { "mapVisInNewWin", "Use a new map window for each new visualisation" }, { "Windows", "Windows" }, { "Map_location", "Map location" },
			{ "Automatic", "Automatic" }, { "Main_window", "Main window" }, { "New_window", "New window" }, { "Print_", "Print..." }, { "Save_", "Save as image..." }, { "Select_what_to_save_", "Select what to save:" } };

	public Object[][] getContents() {
		return contents;
	}
}
