package ui;


public class Res_de extends java.util.ListResourceBundle {
	static final Object[][] contents = new String[][] {
			{ "Select_the_table_for", "W�hlen Sie ein Tabelle um ein Attribut hinzuzuf�gen" },
			{ "Type", "Typ" },
			{ "Integer", "Ganze Zahl" },
			{ "Real", "Reelle Zahl" },
			{ "String", "Text" },
			{ "Default_value", "Standardwert" },
			{ "Specify_a_new", "Neues Attribut definieren" },
			{ "added_to_the_table", " das der Tabelle hinzugef�gt wurde" },
			{ "Attribute", "Attribut " },
			{ "The_attribute_is", "Das Attribut wird gespeichert in Datei " },
			{ "Attributes", "Attribute" },
			{ "include_non_numeric", "nicht-numerische Attribute einschlie�en" },
			{ "Selected_attributes_", "Gew�hlte Attribute:" },
			{ "Selected_attribute_", "Gew�hltes Attribut:" },
			{ "Clear_list", "Liste l�schen" },
			{ "No_attributes", "Keine Attribute ausgew�hlt!" },
			{ "At_least", "Mindestens " },
			{ "Exactly", "Genau " },
			{ "attributes_must_be", " Attribute m�ssen selektiert werden!" },
			{ "No_more_than", "Nicht mehr als " },
			{ "No_values_of_the", "Keine Attributwerte in den Daten gefunden!" },
			{ "All_values_of_the", "Alle Attributwerte sind gleich!" },
			{ "No_calculations", "Keine Berechnungswerkzeuge verf�gbar!" },
			{ "Select_the_table_for1", "W�hlen Sie die Tabelle f�r die Berechnung" },
			{ "Select_attribute_s", "W�hlen Sie Attribut(e) f�r die Berechnung" },
			{ "is_not", " ist nicht " },
			{ "The_method", "Die Methode " },
			{ "applicable_to_the", "anwendbar auf die selektierten Attribute!" },
			{ "Calculate", "Berechnen" },
			{ "Table", "Tabelle \"" },
			{ "No_tables_or_layers", "Es wurden noch keine Tabellen oder Layer geladen!" },
			{ "Specify_the_dataset", "Zu wiederherstellenden Datensatz angeben:" },
			{ "Reload_data", "Daten wiederherstellen" },
			{ "The_data_have_been", "Die Daten wurden wiederhergestellt" },
			{ "File", "Datei" },
			{ "Load_project", "Projekt laden" },
			{ "Load_data_", "Daten laden ..." },
			{ "Reload_data_", "Daten wieder herstellen ..." },
			{ "Save_project", "Projekt speichern" },
			{ "Export_data", "Daten exportieren" },
			{ "Store_data_from_a", "Daten einer Tabelle speichern" },
			{ "Add_attribute", "Attribut hinzuf�gen" },
			{ "Remove_table", "Tabelle entfernen" },
			{ "Join_tables", "Tabelle vereinigen" },
			{ "Remove_map_layer", "Karten-Layer entfernen" },
			{ "Remove_map", "Karte entfernen" },
			{ "Remove_all_data", "Alle Daten entfernen" },
			{ "Quit", "Beenden" },
			{ "Display", "Visualisierung" }, // Descartes UI
			{ "Display_wizard_", "Visualisierungsexperte ..." },
			{ "View_table", "Tabelle ansehen" },
			{ "Clean_the_map", "Karte s�ubern" },
			{ "Another_window", "Anderes Fenster" },
			{ "Calculate_in_a_table", "Tabellenberechnungen" },
			{ "Geographic", "Geographische Berechnungen" },
			{ "Tools", "Werkzeuge" },
			{ "Options", "Optionen" },
			{ "Show_records_options_", "Datensatz-Optionen..." },
			{ "Verify_relationships", "Beziehungen zwischen Variablen verifizieren" },
			{ "Warn_of_misuse", "Vor Missbrauch warnen" },
			{ "Help", "Hilfe" },
			{ "Index", "Index" },
			{ "Decision_support", "Entscheidungsunterst�tzung" },
			{ "About", "Info" },
			{ "About_project", "Projektinfo" },
			{ "Data_Server_URL_", "URL des Daten-Servers:" },
			{ "Data_Server_URL", "URL des Daten-Servers" },
			{ "Select_the_file_with", "Datei mit Projektbeschreibung w�hlen" },
			{ "Select_project_", "Projekt ausw�hlen:" },
			{ "Select_project", "Projekt ausw�hlen" },
			{ "Could_not_open_the", "Stream konnte nicht ge�ffnet werden: " },
			{ "Server_error_", "Server Fehler " },
			{ "The_directory_for", "Verzeichnis f�r Datenspeicherung wurde nicht angegeben" },
			{ "The_script_to_use_for", "Das Skript f�r Datenspeicherung wurde nicht angegeben" },
			{ "What_table_to_remove_", "Welche Tabelle soll entfernt werden?" },
			{ "Confirm", "Best�tigen" },
			{ "Remove_the_table", "Entfernen der Tabelle " },
			{ "What_layer_to_remove_", "Welcher Layer soll entfernt werden?" },
			{ "remove_the_related", "Entfernen der entsprechenden Tabelle" },
			{ "Remove_the_layer", "Entfernen des Layers " },
			{ "and_the_related_table", " und der entsprechenden Tabelle?" },
			{ "Remove_the_current", "Aktuelle Karte entfernen?" },
			{ "Remove_all_the_data_", "Alle Daten entfernen?" },
			{ "Select_the_table_for2", "Tabelle zum Anschauen w�hlen" },
			{ "Select_the_table", "Tabelle w�hlen" },
			{ "Select_table_or_layer", "W�hlen Sie eine Tabelle oder ein Layer" },
			{ "tables", "Tabellen" },
			{ "layers", "Layers" },
			{ "Record_viewing", "Darstellungmodus f�r Datens�tze" },
			{ "Select_the_layers_to", "W�hlen Sie die zu l�schenden Layer" }, // Descartes UI
			{ "Select_attributes", "Attribute ausw�hlen" }, { "Select_the_table_for3", "Tabelle f�r die Visualisierung ausw�hlen" }, { "Select_attribute_s_to", "Attribut(e) f�r die Visualisierung ausw�hlen" }, { "Maps", "Karten" },
			{ "Do_not_build_a_map", "Keine Karten herstellen" }, { "Charts", "Diagramme" }, { "Do_not_build_a_chart", "Keine Diagramme herstellen" }, { "Select_display_type", "Darstellungsweise w�hlen" },
			{ "Select_the_layer_to", "W�hlen Sie das Layer, das mit der Tabelle verkn�pft werden soll" }, { "Currently_displayed", "Momentan dargestellte" }, { "Clear_all", " Nichts ausw�hlen" }, { "Select_all", "Alle ausw�hlen" },
			{ "Click_here_to_get", "Hilfe" }, { "You_can_enable_popup", "Ein Popup-Fenster erm�glicht Ihnen den interaktiven Zugriff auf Datens�tze" },
			{ "You_can_use_separate", "Sie k�nnen sich hiermit die Datens�tze in einem zus�tzlichen Fenster anzeigen lassen" }, { "When_this_is_switched", "When this is switched ON you can see the latest data output in Show Record window" },
			{ "You_can_set_limit_of", "You can set limit of lines used to show data records in popup and Show Record window" }, { "Select_all_attributes", "Select all attributes and add them to Show Record window" },
			{ "Deselect_all", "Deselect all previously selected attributes and remove them from Show Record window" }, { "Set_attributes_showed", "Set attributes showed on all data displays as current selection" },
			{ "When_switched_ON_new", "When switched ON, new attributes are added automatically to the Show Record window" }, { "When_switched_ON", "When switched ON, parental attributes are added automatically to the Show Record window" },
			{ "Object_view", "Parameter f�r Objekt-Ansicht" }, { "Enable_record_display", "Datens�tze im Popup-Fenster darstellen" }, { "Use_persistent_record", "Festes Datensatz-Fenster benutzen" }, { "Show_maximum", "Maximal" },
			{ "lines", "Zeilen anzeigen" }, { "What_to_show_in_the", "Was im Datensatz-Fenster gezeigt werden soll: " }, { "Attributes_on_all", "die Attribute aller ge�ffneten Darstellungen" }, { "Selection_from_list", "eine Listenauswahl" },
			{ "new_attributes_added", "nur die neuen Attribute, die Darstellungen hinzugef�gt wurden" }, { "parents_of_derived", "Ursprungsattribute abgeleiteter Attribute" }, { "Automatically_add_", "Automatisch hinzuf�gen:" },
			{ "Pan_map_to_the_window", "Karte dem Fenster anpassen" }, { "Zoom_In", "Hineinzoomen" }, { "Zoom_Out", "Herauszoomen" }, { "Zoom_Undo", "R�ckg�ngig" }, { "Print", "Ausdrucken" }, { "Save_map_to_file", "Karte speichern in Datei" },
			{ "Drag_Zoom_In", "Ziehen:\nHineinzoomen" }, { "Drag_Move_map", "Ziehen:\nKarte bewegen" }, { "Drag_Select_objects", "Ziehen:\nObjekte ausw�hlen" }, { "deselect", "Objektenauswahl l�schen" }, { "West", "Westen" },
			{ "South_West", "S�d-Westen" }, { "South", "S�den" }, { "South_East", "S�d-Osten" }, { "East", "Osten" }, { "North_East", "Nord-Osten" }, { "North", "Norden" }, { "North_West", "Nord-Westen" }, { "Move_to_", "Nach\n" },
			{ "Legend", "Legende" }, { "Select_what_to_print_", "W�hlen Sie, was gedruckt werden soll:" }, { "Map", "Karte" }, { "Fit_to_minimum_page", "An minimale Seitengr��e anpassen" }, { "Option_", "Option:" }, { "Printing", "Drucken" },
			{ "Print_Map", "Karte drucken" }, { "Printing_map_", "Karte wird gedruckt..." }, { "Printing_legend_", "Legende wird gedruckt..." }, { "Printing_map_and_legend", "Karte und Legende werden gedruckt..." },
			{ "Saving_graphics_into", "Speicherung von Grafiken ist in dieser version des Systems nicht vorgesehen" }, { "Saving", "Speichern" }, { "This_format_is_not", "Dieses Format wird nicht unterst�tzt!" },
			{ "JPEG_image_encoding", "JPEG Enkodierung wird von Java 1.1.x nicht unterst�tzt! Benutzen Sie Java 2 oder eine neuere Version" }, { "Saving_map_", "Karte wird gespeichert..." },
			{ "Select_the_file_to", "Datei zur Kartenspeicherung w�hlen" }, { "Saving_legend_", "Legende wird gespeichert..." }, { "Select_the_file_to1", "Datei zur Legendenspeicherung w�hlen" },
			{ "Select_the_table_to", "Zu exportierende Tabelle w�hlen" }, { "Export_the_table_to", "Export der Tabelle in Datei" }, { "Error_writing_to_the", "Fehler beim Schreiben in Datei: " },
			{ "The_directory_for1", "Das Verzeichnis wurde nicht angegeben!" }, { "The_CGI_script_for", "Das CGI-Skript wwurde nicht angegeben!" }, { "Select_attributes_to", "W�hlen Sie Attribute, die gespeichert werden sollen" },
			{ "Store_the_data_to_the", "Daten speichern in Datei" }, { "Fit_to_the_window", "Dem Fenster anpassen" }, { "Multiply_by", "Multiplizieren mit" }, { "Undo", "R�ckg�ngig" }, { "Manipulate", "Kartenmanipulation" },
			{ "Object_view1", "Objektfenster" }, { "Save_or_print_map", "Save or print map" }, { "CommonGIS", "CommonGIS (fr�her Descartes)" }, { "System_for", "System for Exploratory Analysis of Spatially Referenced Data" },
			{ "Version", "Version" }, { "debug_info", "Debug information" }, { "included", "included" }, { "excluded", "excluded" }, { "no_warranty_string", "Es besteht keine Anspr�che aus dem Lizenzvertag" },
			{ "copyright", "(c) Fraunhofer IAIS 1997-2010" }, { "e-mail", "e-mail gennady.andrienko@iais.fraunhofer.de" }, { "url", "http://www.CommonGIS.com/" },
			{ "development_supported_by_EU", "Development of the system was partly supported by EU" }, { "within_projects", "within funded projects" }, { "commongis_project", "CommonGIS (ESPRIT project 28983, 1998-2001)" },
			{ "spin_project", "SPIN (IST-1999-10536, 2000-2003)" }, { "GIMMI_project", "GIMMI (IST-2001-34245, 2002-2004)" }, { "and_", "and " }, { "commongis_project_url", "http://commongis.jrc.it/" },
			{ "spin_project_url", "http://www.ccg.leeds.ac.uk/spin/" }, { "GIMMI_project_url", "http://services.txt.it/gimmi/" }, { "third_parties_software", "The system includes software modules implemented by third parties:" },
			{ "iitp", "File management utilities by IITP RAS, http://www.iitp.ru/" }, { "uni_Bonn", "Reading OpenGIS simple feature specification by University of Bonn" }, { "uni_Bonn_url", "http://www.giub.uni-bonn.de/exse/results/welcome.html" },
			{ "Java_version_", "Java version " }, { "No_vis_methods_", "No visualisation methods appropriate for the individual maps!" }, { "Choose_vis_method_", "Choose the visualisation method for the individual maps:" },
			{ "together", "zusammen" }, { "Select_layer", "W�hlen Sie den Layer" }, { "Table_join", "Tabelle Vereinigung" }, { "New_table_name", "New table name" }, { "Select_attributes_to_join", "W�hlen Sie Attribut(e) f�r die Vereinigung" },
			{ "Preparing_table_", "Attribute-Vorbereitung: " }, { "Calculating", "Vereinigung: " }, { "_of_", " von " }, { "Done", "Fertig" }, { "All", "Alle" }, { "None", "Keine" }, { "Selected_attributes", "Ausgew�hlte Attribute:\n" },
			{ "From_table", "\nAus die Tabelle " }, { "time_functions", "Zeitfunktionen" }, { "no_attributes", "Keine Attribute gefunden!" }, { "no_params", "Keine Parameter gefunden!" },
			{ "no_numeric_attributes", "Keine Zahlattribute gefunden!!" }, { "time_dep", "depends on a temporal parameter" }, { "par_dep", "depends on a non-temporal parameter" }, { "no_par_dep_attr", "No parameter-dependent attributes found!" },
			{ "depends_on_1", "depends on a parameter." }, { "depends_on_2", "depends on parameters." }, { "depend_on_1", "depend on a parameter." }, { "depend_on_2", "depend on parameters." },
			{ "select_values_1", "Select values of the parameter" }, { "select_values_2", "Select values of each parameter" }, { "Some_chosen_attr", "Some of the attributes you have chosen" }, { "depend_on_params", "depend on parameters." },
			{ "select_values_3", "Select parameter values for each attribute" }, { "select_param_values", "Select parameter values" }, { "individually", "Consider each attribute individually" },
			{ "attribute_selected_", "Das folgende Attribut wurde ausgew�hlt:" }, { "attributes_selected_", "Die folgende Attribute wurden ausgew�hlt:" }, { "confirm_selection", "Confirm selection" }, { "time_analysis", "Time analysis" },
			{ "start_time_functions", "Do you wish to use time-series visualisation?" }, { "Failed_to_load_data", "Fehler beim herstellen der Daten!" }, { "no_layers_with_data", "No layers with thematic data found!" },
			{ "no_tables_to_join", "No tables to join!" }, { "view_links", "Table-layer links" }, { "link", "Link" }, { "Select_a_layer", "W�hle einen Layer" }, { "Select_a_layer_to", "W�hle einen Layer, der mit der Tabelle verkn�pft werden soll" },
			{ "The_table_has_been", "Die Tabelle wurde mit dem Layer verkn�pft " }, { "Choose", "W�hlen" }, { "More", "Mehr" }, { "Choose_single", "W�hlen Sie ein einziges Attribut" }, { "all_values", "alle m�gliche Werte" },
			{ "no_data_in_table", "Keine Daten gefunden in der Tabelle!" }, { "window_name", "Window name" }, { "no_layers_with_2_tables", "Keine Layers mit 2 oder mehr Tabellen" },
			{ "Select_individual_attributes", "Individuelle Attribute wahlen" }, { "Select_tables_to_join", "W�hlen Sie Tabelle f�r die Vereinigung" }, { "special_time_vis", "Special time-series visualisation?" },
			{ "ask_use_special_time_vis", "Do you wish to use one of the following " + "visualisation methods specially designed for time-series data?" }, { "other_vis_methods", "Other visualisation methods" }, { "reorder", "Umstellen" },
			{ "reorder_attrs", "Umstellen die Atribute" }, { "no_map_view", "No map view found!" }, { "mapVisInNewWin", "Use a new map window for each new visualisation" }, { "Windows", "Fenster" }, { "Map_location", "Map location" },
			{ "Automatic", "Automatic" }, { "Main_window", "Main window" }, { "New_window", "New window" }, { "Print_", "Drucken..." }, { "Save_", "Als Bild speichern..." }, { "Select_what_to_save_", "W�hlen Sie was gespeichert werden soll:" } };

	public Object[][] getContents() {
		return contents;
	}
}
